include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
  plugins:
    - custom_lint
  errors:
    # Idiomatic Flutter code has an often unused Key in Widget constructors
    unused_element_parameter: ignore

linter:
  rules:
