FROM node:24-alpine3.21

ENV NODE_ENV $NODE_ENV
ENV BASE_URL $BASE_URL

RUN apk add --no-cache ffmpeg
# "Impact" font
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f

# Install dependencies in the development image
WORKDIR /srv/server
COPY package*.json ./
RUN npm install

COPY data.db ./data.db

COPY tsconfig.json ./

EXPOSE 8080

CMD npm run dev
